// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7ct5XhTD-cKEuZNoAzANDPOELYzlTzg',
    appId: '1:280341375610:web:151b3f6e577399ec70a9c3',
    messagingSenderId: '280341375610',
    projectId: 'medicare-66595',
    authDomain: 'medicare-66595.firebaseapp.com',
    storageBucket: 'medicare-66595.firebasestorage.app',
    measurementId: 'G-EZ1Z2V4TH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe8vuCHmkgKJohmpU97_0mneEOUs5P4Ss',
    appId: '1:280341375610:android:26b44b561573d59270a9c3',
    messagingSenderId: '280341375610',
    projectId: 'medicare-66595',
    storageBucket: 'medicare-66595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAczEoseNm3Juy8xVekjlo57yJoaW7UL9c',
    appId: '1:280341375610:ios:1ab4ab3aa8876bd870a9c3',
    messagingSenderId: '280341375610',
    projectId: 'medicare-66595',
    storageBucket: 'medicare-66595.firebasestorage.app',
    iosBundleId: 'com.example.mediCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAczEoseNm3Juy8xVekjlo57yJoaW7UL9c',
    appId: '1:280341375610:ios:1ab4ab3aa8876bd870a9c3',
    messagingSenderId: '280341375610',
    projectId: 'medicare-66595',
    storageBucket: 'medicare-66595.firebasestorage.app',
    iosBundleId: 'com.example.mediCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7ct5XhTD-cKEuZNoAzANDPOELYzlTzg',
    appId: '1:280341375610:web:2ae0f6c9afabc92270a9c3',
    messagingSenderId: '280341375610',
    projectId: 'medicare-66595',
    authDomain: 'medicare-66595.firebaseapp.com',
    storageBucket: 'medicare-66595.firebasestorage.app',
    measurementId: 'G-Y3CT7H7TPP',
  );
}
